### ISSUE TITLE
Download klappt nicht mehr seit 30.01.2024

### ISSUE THREAD

**Issue by LudwigWen** [esclear/szed#1]
Ursache nach erste Diagnose:

 * https://epaper.sueddeutsche.de/login ist nicht mehr erreichbar.

Hab leider NULL Erfahrung bzgl. Browserautomatisierung.

Gibt es einen fix?

**Comment by esclear** [comment]
Hi,
ich habe das Tool seit bald zehn Jahren nicht mehr verändert und mangels Abo seit vielen Jahren auch nicht mehr verwendet.

Ich vermute auch, dass es in dieser Form auch seit längerer Zeit nicht mehr funktioniert hätte, da die SZ ihr epaper-Portal komplett umgestellt zu haben scheint.
Man müsste das Skript wohl von Grund auf neu schreiben.
